#!/bin/bash
create_db()  {
read -p "Enter DataBase Name: " db_name
if [ -z "$db_name" ] ; then
echo "Error:Database name can't be empty"
elif [[ ! $db_name =~ ^[a-zA-Z] ]]; then
echo "Error: Name must start only with letters"
elif [[ $db_name == *" "* ]]; then
echo "Error: Database name is only 1 word you can use (-,_,$,...)"
elif [ -d DBMS/$db_name ]; then
echo "Error: Database $db_name exists"
else
mkdir DBMS/$db_name
echo "Database has been created successfully ✅ "
fi
}


function list_db {
if [ -z "$(ls -A  DBMS)" ] 
then 
	echo "There is no databases yet" 
else 
	echo "=============================="
	echo "DataBases in the system: "
	echo "=============================="
	ls DBMS
fi

}

function connect_db {
local old_ps3="$PS3"
read -p "Enter DataBase name to connect: " db_name
if [[ -z "$db_name"  ]]
then
	echo "DataBase name cannot be empty!" 
elif [[ ! -d "DBMS/$db_name" ]]
then 
	echo "DataBase not exists!!"
else 
	echo "Connected to $db_name successfully ✅"
	PS3="Choose an operation on table: "
	select  op in "Create Table" "List Tables" "Drop Table" "Insert into Table" "Select from Table" "Delete from Table" "Update Table" "Back to main menu"
	do
		case $REPLY in
			1)create_table "$db_name" ;;
			2)list_tables "$db_name" ;;
			3)drop_table "$db_name" ;;
			4)insert_into "$db_name" ;;
			5)select_table "$db_name" ;;
			6)delete_from_table "$db_name" ;;
			7)update_table "$db_name" ;;
			8)echo "Back to main menu"
				 break ;;
			*)echo "Invalid option, Try again!!"			
		esac
	done
fi
	PS3="$old_ps3"


}

function drop_db {
read -p "Enter DataBase name to be dropped: " db_name
if [[ -z "$db_name"  ]]
then
        echo "DataBase name cannot be empty!"
elif [[ ! -d "DBMS/$db_name" ]]
then 
        echo "DataBase not exists!!"
else 
	read -p "Are you sure to drop $db_name? (Y\N)" confirm
	if [[ "$confirm" =~ ^[Yy] ]]
	then
		rm -r "DBMS/$db_name"
		echo "DataBase $db_name dropped successfully ✅"
	else
		echo "Drop Cancelled!"
	fi

fi

}
