#!/bin/bash
function create_table {
    local db=$1
    local old_ps3="$PS3"
    read -p "Enter the table to create:  " tbl_name

    if [ -z "$tbl_name" ] ; then
        echo "Error:Table name can't be empty"
    elif [[ -f "DBMS/$db/$tbl_name.meta" ]] ; then
        echo "Error: $tbl_name is already existed "
    elif [[ ! $tbl_name =~ ^[a-zA-Z] ]]; then
        echo "Error: Name must start only with letters"
    elif [[ $tbl_name == *" "* ]]; then
        echo "Error: table name is only 1 word you can use (-,_,$,...)"
    else
        typeset -i num_col
		while true
		do
        	read -p "Enter number of columns you wanted: " num_col
			if [[ $num_col -eq 0 ]] ; then
            	echo "you must enter a number greater than 0 !!"
        	else
				break
			fi
		done

        
            cols_names=""
            cols_types=""
            col_pk=""

            for (( i=1; i<=$num_col; i++ )); do
                read -p "enter name for column $i: " col_name

                if [ -z "$col_name" ] ; then
                    echo "Error:Column name can't be empty"
                    i=$i-1
                elif [[ ":$cols_names:" == *":$col_name"*  ]] ; then
                    echo "Error: $col_name is already existed "
                    i=$i-1
                elif [[ ! $col_name =~ ^[a-zA-Z] ]]; then
                    echo "Error: Name must start only with letters"
                    i=$i-1
                elif [[ $col_name == *" "* ]]; then
                    echo "Error: Column name is only 1 word you can use (-,_,$,...)"
                    i=$i-1
                else
                    PS3="Choose type for $col_name: "

                    select type in "int" "string"
                    do
                        case $type in
                            int|string)
                                col_type=$type
                                break
                                ;;
                            *)
                                echo "Invalid option"
                                ;;
                        esac
                    done

                    if [ -z "$col_pk" ] ; then
                        read -p "Do you want $col_name a primary key? (yes/No) : " is_pk
                        if [[ "$is_pk" =~ ^[yY] ]] ; then
                            col_pk=$col_name
                        fi
                    fi

                    if [[ $i -eq $num_col ]]; then
                        cols_names+=$col_name
                        cols_types+=$col_type
                    else
                        cols_names+="$col_name:"
                        cols_types+="$col_type:"
                    fi
                fi
            done

            echo "$cols_names" > "DBMS/$db/$tbl_name.meta"
            echo "$cols_types" >> "DBMS/$db/$tbl_name.meta"
            echo "PK:$col_pk" >> "DBMS/$db/$tbl_name.meta"
	    touch "DBMS/$db/$tbl_name.data"

            echo "Table has been created successfully ✅"
        
    fi
            PS3="$old_ps3"

}


function insert_into {
	local db=$1
	read -p "Enter table name: " tbl_name
	while true
	do
		if [ ! -f "DBMS/$db/$tbl_name.meta" ]
		then
			echo "Table not exists!!"
			read -p "Enter table name: " tbl_name
		else 
			break
		fi 	
	done
	record=""
	col_names_arr=($(awk -F: 'NR==1 {for(i=1;i<=NF;i++) print $i}' "DBMS/$db/$tbl_name.meta"))
	col_types_arr=($(awk -F: 'NR==2 {for(i=1;i<=NF;i++) print $i}' "DBMS/$db/$tbl_name.meta"))
	pk=$(awk -F: 'NR==3 {print $2}' "DBMS/$db/$tbl_name.meta")
	#pk_index=$(awk -F: -v primary="$pk" ' NR==1 { for(i=1;i<=NF;i++) if($i==primary) print i }' "DBMS/$db/$tbl_name.meta")
	pk_index=-1 
	for i in "${!col_names_arr[@]}"
		 do
   			if [[ "${col_names_arr[$i]}" == "$pk" ]]; then
       			pk_index=$((i + 1)) 
       			break
   			fi
		done
	col_num=${#col_names_arr[@]}
	for((j=0;j<$col_num;j++))
	do
		read -p "Enter column ${col_names_arr[$j]} (${col_types_arr[$j]}): " val
		
		if [ -z "$val" ]
		then
			echo "Value cannot be empty!!"
			((--j))
			continue
		elif [[ "${col_types_arr[$j]}" == "int" ]] && [[ ! "$val" =~ ^[0-9]+$ ]]
		then
			echo "You must enter an integer value"
			((--j))
			continue
		elif [[ "${col_types_arr[$j]}" == "string" ]] && [[ ! "$val" =~ ^[A-Za-z0-9]+$ ]]
		then
			echo "You must enter a string value"
			((--j))
			continue
		elif [[ "${col_names_arr[$j]}" == "$pk"  ]]
		then
			check=$(awk -F: -v col="$pk_index" -v new_val="$val" '$col == new_val {print $0}' "DBMS/$db/$tbl_name.data")
			if [ ! -z "$check" ]
			then
			echo "Primary key cannot be duplicated!!"
			((--j))
			continue
			fi	
		fi
		record+="$val"
		if [ $j -lt $((col_num-1)) ]
		then
    			record+=":"
		fi
	done

	echo "$record" >> "DBMS/$db/$tbl_name.data"

}

function list_tables {
	local db=$1
	echo "--- Tables in Database: $db ---"
	if [ -z "$(ls "DBMS/$db")" ]; then
		echo "No tables Found in this DB "
	else
		ls "DBMS/$db" | grep ".data$" | cut -d '.' -f1 
	fi
	echo "-------------------------------"
}

function drop_table {
	local db=$1
	read -p "enter the table name you want to drop: " tbl_name
	if [ -z "$tbl_name" ] ; then
        	echo "Error: Table name can't be empty! ❌"

	elif [[ ! -f "DBMS/$db/$tbl_name.meta" ]] ; then
		echo "Error: Table '$tbl_name' does not exist! ❌"
	else
		read -p "Are you sure you want to delete '$tbl_name'? (y/n) " confirm
		if [[ "$confirm" =~ ^[yY] ]]; then
			rm -r "DBMS/$db/$tbl_name.meta"
			rm -r "DBMS/$db/$tbl_name.data"
			echo "Table has been dropped successfully✅"
		else
			echo "Drop operation canceled. 😌"
		fi
	fi

}

	
function select_table {
	local db=$1
	
	
	while true
	do
		read -p "Enter table name: " tbl_name
		if [ ! -f "DBMS/$db/$tbl_name.meta" ]
		then 
		echo "Table $tbl_name doesnot exist!!"
		else 
			break
		fi
	done

	echo "----------------------------"
	echo "1) Select All"
	echo "2) Select by a specific column"
	echo "----------------------------"
	  
	read -p "Select an option: " select_op
	
	case $select_op in
	1) 	echo "====================================================="
		echo "All values of table $tbl_name: "
	 	echo "====================================================="
		{ head -1 "DBMS/$db/$tbl_name.meta"; cat "DBMS/$db/$tbl_name.data"; } | column -t -s ":"
		echo "======================================================"
		  ;;
	2) 	
		echo "------------------------------------------"
		echo "Available columns: "
		head -1 "DBMS/$db/$tbl_name.meta" | tr ":" " : "
		echo "------------------------------------------"
		while true
		do						
			read -p "Enter column name to be filterd with: " col_name
			col_index=$(awk -F: -v cn="$col_name" ' NR==1 { for(i=1;i<=NF;i++) if(cn==$i) print i }' "DBMS/$db/$tbl_name.meta")
			if [ -z "$col_index" ]
			then
				echo "Column doesn't exist!!"
			else
				break
			fi
		done
		read -p "Enter value of column $col_name to serach with: " search_val
		echo "======================================================"
		echo "Search Results"
		echo "======================================================"
		{
		head -1 "DBMS/$db/$tbl_name.meta"
		awk -F: -v ci="$col_index" -v sv="$search_val" '$ci == sv {print $0}' "DBMS/$db/$tbl_name.data"
		} | column -t -s ":"
		echo "======================================================"
		;;
	*) echo "Invalid option!" ;; 
	esac
	
}	


function update_table {
	db=$1
	while true
        do
                read -p "Enter table name: " tbl_name
                if [ ! -f "DBMS/$db/$tbl_name.meta" ]
                then 
                echo "Table $tbl_name doesnot exist!!"
                else 
                        break
                fi
        done

	        echo "------------------------------------------"
                echo "Available columns: "
                head -1 "DBMS/$db/$tbl_name.meta" | tr ":" " : "
                echo "------------------------------------------"
                while true
                do
                        read -p "Enter the column name to use for locating the record (WHERE): " col_name
                        col_index=$(awk -F: -v cn="$col_name" ' NR==1 { for(i=1;i<=NF;i++) if(cn==$i) print i }' "DBMS/$db/$tbl_name.meta")
                        if [ -z "$col_index" ]
                        then
                                echo "Column doesn't exist!!"
                        else
                                break
                        fi
                done
                read -p "Enter the value of [$col_name] for the record you want to update: " search_val
		where_check=$(awk -F: -v ci="$col_index" -v val="$search_val" '$ci == val { print $0 }'  "DBMS/$db/$tbl_name.data")
		if [ ! -z "$where_check" ]
		then
	#	echo "======================================================"
        #        echo "Records wanted to be updated: "
        #        echo "======================================================"
        #        {
        #       head -1 "DBMS/$db/$tbl_name.meta"
        #        awk -F: -v ci="$col_index" -v sv="$search_val" '$ci == sv {print $0}' "DBMS/$db/$tbl_name.data"
        #        } | column -t -s ":"
        #         echo "======================================================"

		while true
                do
                        read -p "Enter the column name to be updated: " col_update
                        col_index_update=$(awk -F: -v cn="$col_update" ' NR==1 { for(i=1;i<=NF;i++) if(cn==$i) print i }' "DBMS/$db/$tbl_name.meta")
                        if [ -z "$col_index_update" ]
                        then
                                echo "Column doesn't exist!!"
                        else
                                break
                        fi
                done
		pk=$(awk -F: ' NR==3 {print $2}' "DBMS/$db/$tbl_name.meta")
		pk_index=$(awk -F: -v primary="$pk" ' NR==1 { for(i=1;i<=NF;i++) if($i==primary) print i }' "DBMS/$db/$tbl_name.meta")
		col_upated_datatype=$(awk -F: -v ci="$col_index_update"  ' NR==2 {print $ci}' "DBMS/$db/$tbl_name.meta")

		while true
		do
			read -p "Enter the new value of [$col_update]: " new_val
			check=$(awk -F: -v col="$pk_index" -v val="$new_val" '$col == val {print $0}' "DBMS/$db/$tbl_name.data")
			if [ -z "$new_val" ]
			then
				echo "Value cann't be empty!!"
			elif [[ "$col_upated_datatype" == "int" ]] && [[ ! "$new_val" =~ ^[0-9]+$ ]]
                	then
                        	echo "You must enter an integer value"
                	elif [[ "$col_upated_datatype" == "string" ]] && [[ ! "$new_val" =~ ^[A-Za-z0-9]+$ ]]
                	then
                        	echo "You must enter a string value"
			elif [[ "$col_update" == "$pk"  ]] && [ ! -z "$check" ]
                	then             	
                        	echo "Primary key cannot be duplicated!!"
                        
			else
				break
                	fi
		done	
	awk -F: -v ci_w="$col_index" -v val_w="$search_val" -v cu="$col_index_update" -v new_val="$new_val" 'BEGIN{OFS=":"} { if ( $ci_w == val_w ) $cu = new_val; print $0 }' "DBMS/$db/$tbl_name.data" > "DBMS/$db/$tbl_name.tmp" && mv "DBMS/$db/$tbl_name.tmp" "DBMS/$db/$tbl_name.data"
	echo "update has been done successfully "
	echo "==================================================" 
		
		else 
			echo "There are no records match this condition [$col_name]=[$search_val] !!"
		fi

}



function delete_from_table {
    db=$1
    while true; do
        read -p "Enter table name: " tbl_name
        if [ ! -f "DBMS/$db/$tbl_name.meta" ]; then
            echo "Table $tbl_name does not exist!!"
        else
            break
        fi
    done
    echo "1) delete all from table (truncate)"
    echo "2) delete using where"
    read -p "Choose an option: " op
    case "$op" in 
	1) echo "⚠️ WARNING: You are about to delete the whole table $tbl_name "
  	read -p "Are you sure? (y/n): " confirm
	if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
		> "DBMS/$db/$tbl_name.data"
        	echo "------------------------------------------"
		echo "All records deleted successfully! ✨"
        	echo "Table [$tbl_name] is now empty."
        	echo "------------------------------------------"
	else
		echo "operation Canceled ❌"
	fi 
	;;

	2)
    echo "------------------------------------------"
    echo "Available columns: "
    head -1 "DBMS/$db/$tbl_name.meta" | tr ":" " : "
    echo "------------------------------------------"

    while true; do
	
	read -p "enter the column name to use for locating the record (WHERE): " col_name

	col_index=$(awk -F: -v cn="$col_name" 'NR==1 {for(i=1;i<=NF;i++) if (cn==$i) print i}' "DBMS/$db/$tbl_name.meta")
	if [ -z "$col_index" ]; then
		echo "Column doesn't exist !!"
	else
		break
	fi
   done
   read -p "Enter the value of [$col_name] to delete the record: " search_val
   where_check=$(awk -F: -v ci="$col_index" -v val="$search_val" '$ci == val { print $0 }'  "DBMS/$db/$tbl_name.data")
   if [ ! -z "$where_check" ] 
   then
   echo "⚠️ WARNING: You are about to delete records where [$col_name] is [$search_val]."
   read -p "Are you sure? (y/n): " confirm
    
    if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
        
        awk -F: -v ci="$col_index" -v sv="$search_val" '$ci != sv {print $0}' "DBMS/$db/$tbl_name.data" > "DBMS/$db/$tbl_name.tmp" && mv "DBMS/$db/$tbl_name.tmp" "DBMS/$db/$tbl_name.data"
        echo "------------------------------------------"
        echo "Deletion completed successfully! ✅"
        echo "------------------------------------------"
    else
        echo "Operation canceled. ❌"
    fi
    # ---------------------------------- 
  else
	echo "there is no record matching your input"
  fi
;;
*) echo "invalid option"
esac  
}
	
	
